Repository greenpeace/planet4-builder, pull requests merged in 2019-02, with the labels that each got.

#19 Feature/shellcheck
  Makefile
  src/bake.sh
  src/configure_redis.sh
  src/flush_redis.sh
  src/ls.sh
  src/rewrite_app_repos.sh
  src/run_post_deploy_scripts.sh
  src/sql_create_sync_file.sh
  src/sql_to_sync_site.sh
Labels: enhancement

#20 Add Hadolint Dockerfile linting
  .hadolint.yaml
  Makefile
Labels: enhancement

#18 Bug/sync script for no apphostpath
  src/sql_to_sync_site.sh
Labels: Review and Merge

#17 PLANET-3163 Rationalise post deploy scripts
  src/Makefile
  src/bake.sh
  src/run_post_deploy_scripts.sh
Labels: Review and Merge, 🍾 Good PR
